version: '3'

services:
  spring-docker:
    container_name: spring-boot-docker-cassandra_1
    build:
      context: .
    image: 'spring-docker_spring-boot-docker-cassandra'
    ports:
      - 4070:4070
    restart: always
    links:
      - cassandra
    depends_on:
      - cassandra
  cassandra:
    image: 'cassandra:3'
    container_name: cassandra
    ports:
      - 9042:9042
      - 7000:7000
      - 9160:9160
      - 7199:7199
